---
deployment:
  tasks:
    - cloudlinux-selector install-modules --json --interpreter nodejs --app-root repository
    - cloudlinux-selector run-script --json --interpreter nodejs --app-root repository --script-name build
    - rsync --delete -acv --exclude=".*" ~/repository/build/ ~/repository/public/ ~/public_html
    - kill -9 $(pgrep -f node)
    - cloudlinux-selector start --json --interpreter nodejs --app-root repository
    - rm -rf ~/repository/build/